service: http-example

plugins:
  - serverless-healthcheck
  - serverless-offline

provider:
  memorySize: 128
  name: aws
  region: us-east-1 # default
  runtime: nodejs12.x
  stage: dev
  versionFunctions: false

custom:
  healthcheck:
    memorySize: 256
    name: '${self:provider.stage}-healthcheck'
    schedule: rate(5 minutes)

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
          healthcheck:
            format:
              name: 'GET: Basic Function call'
  helloWithParameters:
    handler: handler.helloWithParameters
    events:
      - http:
          method: get
          path: hello/{id}
          healthcheck:
            params: {"id":"test world"}
            format:
              name: 'GET: Function with path parameters'
  helloWithBody:
    handler: handler.helloWithBody
    events:
      - http:
          method: post
          path: hello
          healthcheck:
            params: {"hello":"test world"}
            format:
              name: 'POST: Function with body'
